-- Generated by nomarkoo.keyboard-layout. Edit the plugin settings, not this file.
hl.config({
  input = {
    kb_layout = "us,ru",
    kb_variant = ",",
    kb_options = "compose:caps,shift:both_capslock_cancel,grp:alt_shift_toggle",
  },
})

